# remap prefix from 'C-b' to 'C-x'
unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

set -g  default-terminal                "tmux-256color"
set -ga terminal-overrides              ",xterm-*:Tc"
set -g  escape-time                     0
set -g  allow-rename                    off
set -g  base-index                      1
set -g  renumber-windows                on
setw -g pane-base-index                 1
set -g  mouse                           on
set -g  mode-keys                       vi
set -g  status-keys                     vi
set -g  focus-events                    on
set -g  history-limit                   2000
set -g  status-position                 top
set -g  status-style                    bg=black,fg=green
set -g  status-left                     "⎡#S⎤ "
set -g  status-right                    ""
set -g  window-status-current-format    "#I:#W#{?window_zoomed_flag,*,}"
set -g  window-status-current-style     bg=green,fg=black

bind c new-window
bind 0 kill-pane

# Choose window
unbind s
bind b choose-tree -w

# Split panes
bind 3 split-window -h
bind 2 split-window -v
unbind '"'
unbind %

# Kill window
bind k confirm kill-window

# Source the conf file
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf reloaded"

# Copy to system clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# Kill server
bind K kill-server
