ZSH=$HOME/dotfiles/zsh

# History config
export HISTFILE=~/.zsh_history
export HISTSIZE=10
export SAVEHIST=10

# Aliases
source $ZSH/aliases.zsh

# GnuPG
export GPG_TTY=$(tty)

# Android SDK
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/rahul/miniforge3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/rahul/miniforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/rahul/miniforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/rahul/miniforge3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
